{
  "clean": true,
  "sdk": "macosx",
  "author": "Galen Rhodes",
  "author_url": "https://blog.projectgalen.com",
  "github_url": "https://github.com/GalenRhodes/Chadakoin",
  "github_file_prefix": "https://github.com/GalenRhodes/Chadakoin/blob/master",
  "theme": "fullwidth",
  "use_safe_filenames": true,
  "min_acl": "public",
  "undocumented_text": "",
  "title": "Chadakoin©",
  "swift_build_tool": "xcodebuild",
  "build_tool_arguments": [ "-scheme", "Chadakoin", "-jobs", "8", ],
  "separate_global_declarations": true,
},
